FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.11.3@sha256:6f76889df653393bfaf42b12735f380bfb0336532fcdca8560fef2777dd944da
MAINTAINER yaphetsglhf@gmail.com
