FROM gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.11.3@sha256:add85f33c5ac0aa02712ec6e6caad3d4bb7faa33043c5ca252a824b050b4b8e2
RUN apk add python3
MAINTAINER yaphetsglhf@gmail.com
